### ISSUE TITLE
It does not preserve per-argument type comments

### ISSUE THREAD

**Issue by mitar** [mbdevpl/typed-astunparse#2]
This strips per-argument type comments (example taken from [PEP 484](https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code)):

```
code = '''
def send_email(address,     # type: Union[str, List[str]]
               sender,      # type: str
               cc,          # type: Optional[List[str]]
               bcc,         # type: Optional[List[str]]
               subject='',
               body=None    # type: List[str]
               ):
    # type: (...) -> bool
    """Send an email message.  Return True if successful."""
    pass
'''

import typed_ast.ast3
import typed_astunparse

print(typed_astunparse.unparse(typed_ast.ast3.parse(code)))
```

Output is:

```
def send_email(address, sender, cc, bcc, subject='', body=None):
    # type: (...) -> bool
    'Send an email message.  Return True if successful.'
    pass
```

**Comment by mbdevpl** [comment]
Thanks for reporting, will look into that!

**Comment by mitar** [comment]
(Also see that the docstring does not use `"""`.)

**Comment by mbdevpl** [comment]
I've verified that the per-argument type comments are indeed not working. I'll fix it.

However, the docstring issue is out of scope for this unparser. There was a similar issue upstream (astunparse): https://github.com/simonpercivall/astunparse/issues/13 however it was closed.

I'm working towards implementing proper docstring unparsing, (as well as arbitrary comment parsing and unparsing) in a different module: https://github.com/mbdevpl/horast however it's not nearly ready yet.

**Comment by mbdevpl** [comment]
And, there seems to be an issue in `typed_ast` with parsing per-argument type comments in all cases: https://github.com/python/typed_ast/issues/58 so even if I generate valid code, in some cases I actually cannot verify its validity.

**Comment by mitar** [comment]
Thanks for looking into this.

**Comment by mitar** [comment]
(BTW, I used your project here: https://github.com/nvbn/py-backwards/pull/44)

**Comment by mbdevpl** [comment]
Not minding the issue with typed_ast (hopefully it'll get resolved someday) I added the per-argument type comment unparsing and released https://pypi.python.org/pypi/typed-astunparse/2.0.2

**Comment by mitar** [comment]
Oho! Thanks!

**Comment by mbdevpl** [comment]
Oh, and BTW, I just found out that docstrings might be properly stored in AST starting from Python 3.7 - if they will be, then I guess astunparse and typed_astunparse will handle them properly. https://bugs.python.org/issue29463
